apiVersion: v1    
kind: Namespace
metadata:
  name: all
---
apiVersion: v1
kind: Service
metadata:
  name: all-nodeport
  namespace: all
spec:
  selector:
    app: all
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: all-server
  namespace: all
  labels:
    app: all
spec:
  replicas: 1
  selector:
    matchLabels:
       app: all
  template:
    metadata:
      labels:
        app: all
    spec:
      containers:
      - image: 548021806095.dkr.ecr.ap-northeast-2.amazonaws.com/test-ecr:all3
        name: all-server
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-alb
  namespace: all
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: all-nodeport
            port:
              number: 80

